// Automatically generated by astro-icon
// 896f97f73332b4647e531f59c047ffd769d870600a26189ee5c2e27a3f065bd0

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "adguard"
		| "cartao"
		| "cloud"
		| "globe"
		| "portifa"
		| "rss";
}